Web/bell_system/urls.py
# bell_system/urls.py

from django.urls import path
from . import views

app_name = 'bell_system'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:route_id>/', views.detail, name='detail'),
]

Web/livinglab/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bell_system/', include('bell_system.urls')),
]

Web/bell_system/models.py
from django.db import models

# Create your models here.
# bell_system/models.py

from django.db import models

class BusRoute(models.Model):
    route_number = models.CharField(max_length=10)
    description = models.TextField()

    def __str__(self):
        return self.route_number

class BusStop(models.Model):
    route = models.ForeignKey(BusRoute, related_name='bus_stops', on_delete=models.CASCADE)
    stop_name = models.CharField(max_length=100)

    def __str__(self):
        return self.stop_name

Web/bell_system/views.py
# bell_system/views.py

from django.shortcuts import get_object_or_404, render
from .models import BusRoute

def index(request):
    routes = BusRoute.objects.all()
    return render(request, 'bell_system/index.html', {'routes': routes})

def detail(request, route_id):
    route = get_object_or_404(BusRoute, pk=route_id)
    return render(request, 'bell_system/detail.html', {'route': route})

Web/bell_system/templates/bell_system/detail.html
<!-- bell_system/templates/bell_system/detail.html -->

<!DOCTYPE html>
<html>
<head>
    <title>{{ route.route_number }} - 시내버스 승차벨 시스템</title>
</head>
<body>
    <h1>{{ route.route_number }} - 시내버스 승차벨 시스템</h1>
    <p>{{ route.description }}</p>
    <h2>정류장 목록</h2>
    <ul>
        {% for stop in route.bus_stops.all %}
            <li>{{ stop.stop_name }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'bell_system:index' %}">Back to Index</a>
</body>
</html>

Web/bell_system/templates/bell_system/index.html
<!-- bell_system/templates/bell_system/index.html -->

<!DOCTYPE html>
<html>
<head>
    <title>시내버스 승차벨 시스템</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>시내버스 승차벨 시스템</h1>
        <div class="row">
            {% for route in routes %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ route.route_number }}</h5>
                            <p class="card-text">{{ route.description }}</p>
                            <a href="{% url 'bell_system:detail' route.id %}" class="btn btn-primary">세부 정보 보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>